<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <groupId>com.sxpcwlkj</groupId>
        <artifactId>mms-modules</artifactId>
        <version>${revision}</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>
    <artifactId>mms-demo</artifactId>
    <description>演示模块</description>
    <dependencies>
        <dependency>
            <groupId>com.sxpcwlkj</groupId>
            <artifactId>mms-framework</artifactId>
        </dependency>
        <dependency>
            <groupId>com.sxpcwlkj</groupId>
            <artifactId>mms-wx</artifactId>
        </dependency>
        <dependency>
            <groupId>com.sxpcwlkj</groupId>
            <artifactId>mms-aliyun</artifactId>
        </dependency>
        <dependency>
            <groupId>com.sxpcwlkj</groupId>
            <artifactId>mms-sms</artifactId>
        </dependency>
        <dependency>
            <groupId>com.sxpcwlkj</groupId>
            <artifactId>mms-email</artifactId>
        </dependency>
        <dependency>
            <groupId>com.sxpcwlkj</groupId>
            <artifactId>mms-oss</artifactId>
        </dependency>
        <dependency>
            <groupId>com.sxpcwlkj</groupId>
            <artifactId>mms-websocket</artifactId>
        </dependency>
        <dependency>
            <groupId>com.sxpcwlkj</groupId>
            <artifactId>mms-mq</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>

    </dependencies>

</project>
