<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.sxpcwlkj</groupId>
        <artifactId>mms-modules</artifactId>
        <version>${revision}</version>
    </parent>

    <artifactId>mms-websocket</artifactId>
    <name>mms-websocket</name>
    <description>websocket应用模块</description>
    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <dependencies>
        <!--SpringBoot整合WebSocket-->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-websocket</artifactId>
        </dependency>
        <!-- 核销共模块-->
        <dependency>
            <groupId>com.sxpcwlkj</groupId>
            <artifactId>mms-framework</artifactId>
        </dependency>
        <dependency>
            <groupId>com.sxpcwlkj</groupId>
            <artifactId>mms-redis</artifactId>
        </dependency>
        <dependency>
            <groupId>com.sxpcwlkj</groupId>
            <artifactId>mms-authority</artifactId>
        </dependency>
        <!-- 为了支持JSR-305注解-->
        <dependency>
            <groupId>com.google.code.findbugs</groupId>
            <artifactId>jsr305</artifactId>
            <version>3.0.2</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>

</project>
