--- # SBA 服务端
server:
  # 端口
  port: 9001
--- # Spring项目名
spring:
  application:
    name: MMS Monitor

--- # Spring Boot Admin
spring:
  boot:
    admin:
      client:
        enabled: true                 #启用/禁用
        instance:
          service-host-type: IP
        # Spring Boot Admin
        url: http://localhost:9001    #监控服务器端地址
        username: admin               #账号
        password: 123456              #密码

--- # Actuator 监控端点的配置项
management:
  endpoints:
    enabled-by-default: true #暴露所有端点信息
    web:
      exposure:
        include: '*' #以web方式暴露
  endpoint:
    health:
      show-details: ALWAYS
    logfile:
      external-file: ./logs/monitor-console.log


