version: '3.8'

services:
  # 品创网络-MMS
  mms-admin:
    image: sxpcwlkj/mms-admin:1.0.0
    container_name: mms-admin
    environment:
      # 时区上海
      TZ: Asia/Shanghai
    volumes:
      # 配置文件
      - /docker/sxpcwlkj/mms-admin/logs/:/sxpcwlkj/mms-admin/logs
      - /docker/sxpcwlkj/mms-admin/files/:/sxpcwlkj/mms-admin/files
    privileged: true
    network_mode: "host"
