<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.sxpcwlkj</groupId>
        <artifactId>mms-servers</artifactId>
        <version>${revision}</version>
    </parent>
    <packaging>pom</packaging>
    <artifactId>mms-bbs-api</artifactId>
    <description>论坛API服务</description>

    <properties>
        <maven.compiler.source>17</maven.compiler.source>
        <maven.compiler.target>17</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>
    <dependencies>
        <!-- 后台管理系统核心包 -->
        <dependency>
            <groupId>com.sxpcwlkj</groupId>
            <artifactId>mms-framework</artifactId>
        </dependency>
        <dependency>
            <groupId>com.sxpcwlkj</groupId>
            <artifactId>mms-oss</artifactId>
            <exclusions>
                <!-- 解决slf4j冲突  -->
                <exclusion>
                    <artifactId>slf4j-reload4j</artifactId>
                    <groupId>org.slf4j</groupId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>com.sxpcwlkj</groupId>
            <artifactId>mms-sms</artifactId>
        </dependency>
        <dependency>
            <groupId>com.sxpcwlkj</groupId>
            <artifactId>mms-redis</artifactId>
        </dependency>
        <dependency>
            <groupId>com.sxpcwlkj</groupId>
            <artifactId>mms-wx</artifactId>
        </dependency>
    </dependencies>


</project>
