<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.sxpcwlkj</groupId>
        <artifactId>mms</artifactId>
        <version>${revision}</version>
    </parent>
    <packaging>pom</packaging>
    <artifactId>mms-modules</artifactId>
    <description>应用模块集</description>

    <properties>
        <java.version>21</java.version>
    </properties>
    <modules>
        <module>mms-common</module>
        <module>mms-plugin-api</module>
        <module>mms-plugin-host</module>
        <module>mms-framework</module>
        <module>mms-mq</module>
        <module>mms-wx</module>
        <module>mms-aliyun</module>
        <module>mms-oss</module>
        <module>mms-sms</module>
        <module>mms-email</module>
        <module>mms-redis</module>
        <module>mms-demo</module>
        <module>mms-websocket</module>
        <module>mms-authority</module>
        <module>mms-datasource</module>
        <module>mms-gen</module>
        <module>mms-ai</module>
        <module>mms-thymeleaf</module>
        <module>mms-log</module>
        <module>mms-system</module>
    </modules>

</project>
